version: "3"

services: 
  mysql:
    image: mysql:5
    container_name: restaurant-sql
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    ports: 
      - 3306:3306
    restart: always
  phpadmin:
    image: phpmyadmin/phpmyadmin:4.8
    container_name: restaurant-admin
    links: 
      - mysql
    environment: 
      PMA_HOST: mysql
      PMA_PORT: 3306
    restart: always
    ports: 
      - 8081:80